spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/study
    username: dev
    password: dev

  sql:
    init:
      platform: postgres
      data-locations: classpath:sql/data-${spring.sql.init.platform}.sql

  jpa:
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: mvmaniaz@gmail.com
    password: icgomctxfrtwhypx
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true
