spring:
  application:
    name: study

  profiles:
    active: local

  datasource:
    initialization-mode: always
    platform: h2
    data: classpath:sql/data-${spring.datasource.platform}.sql

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  devtools:
    restart.enabled: false
    livereload.enabled: true

server:
  tomcat:
    max-http-form-post-size: 5MB

logging:
  level:
    io.devfactory: debug
    org.hibernate.SQL: debug
    org.springframework: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
