spring:
  application:
    name: study

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  devtools:
    restart.enabled: false
    livereload.enabled: true

logging:
  level:
    io.devfactory: debug
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
