spring:
  application:
    name: study

  profiles:
    active: dev

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  devtools:
    restart.enabled: false
    livereload.enabled: true

  # HTML <FORM>에서 th:method에서 PUT 또는 DELETE를 사용해서 보내는 _method를 사용해서  @PutMapping과 @DeleteMapping으로 요청을 맵핑.
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  tomcat:
    max-http-form-post-size: 5MB

logging:
  level:
    io.devfactory: debug
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

app:
  host: http://localhost:8080
