spring:
  application:
    name: study

  profiles:
    active: dev

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  devtools:
    restart.enabled: false
    livereload.enabled: true

server:
  tomcat:
    max-http-form-post-size: 5MB

logging:
  level:
    io.devfactory: debug
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

app:
  host: http://localhost:8080
